let step=1;let selectedDate="17/08/2026";let selectedTime="08:00";
const steps=[...document.querySelectorAll(".booking-step")], progress=[...document.querySelectorAll(".progress-step")];
function render(){steps.forEach(s=>s.classList.toggle("active",Number(s.dataset.step)===step));progress.forEach(p=>p.classList.toggle("active",Number(p.dataset.progress)<=step));if(step===3)updateSummary()}
document.querySelectorAll(".next-step").forEach(b=>b.addEventListener("click",()=>{step=Math.min(3,step+1);render()}));
document.querySelectorAll(".prev-step").forEach(b=>b.addEventListener("click",()=>{step=Math.max(1,step-1);render()}));
document.querySelectorAll(".date-option").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll(".date-option").forEach(x=>x.classList.remove("active"));b.classList.add("active");selectedDate=b.dataset.date}));
document.querySelectorAll(".time-option").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll(".time-option").forEach(x=>x.classList.remove("active"));b.classList.add("active");selectedTime=b.textContent}));
function getService(){return document.querySelector('input[name="service"]:checked').value}
function updateSummary(){document.getElementById("bookingSummary").innerHTML=`<b>Resumo do agendamento</b><br>${getService()} · ${document.getElementById("bookingDoctor").value}<br>${selectedDate} às ${selectedTime}`}
document.getElementById("bookingForm").addEventListener("submit",e=>{e.preventDefault();const data={patient:document.getElementById("patientName").value,cpf:document.getElementById("patientCpf").value,phone:document.getElementById("patientPhone").value,email:document.getElementById("patientEmail").value,service:getService(),doctor:document.getElementById("bookingDoctor").value,date:selectedDate,time:selectedTime,source:"paciente"};const all=JSON.parse(localStorage.getItem("odontoAppointments")||"[]");all.push(data);localStorage.setItem("odontoAppointments",JSON.stringify(all));steps.forEach(s=>s.classList.remove("active"));document.querySelector(".booking-progress").style.display="none";const success=document.getElementById("bookingSuccess");success.classList.add("show");document.getElementById("successDetails").innerHTML=`<b>${data.service}</b><br>${data.doctor}<br>${data.date} às ${data.time}<br>Paciente: ${data.patient}`});
document.getElementById("newBooking").addEventListener("click",()=>location.reload());